FUZZER_NAME := 'rj_fuzzer'
PROJECT_DIR := absolute_path(".")
PROFILE := 'release'
PROFILE_DIR := 'release'
CARGO_TARGET_DIR := env("CARGO_TARGET_DIR", "target")
FUZZER := CARGO_TARGET_DIR / PROFILE_DIR / FUZZER_NAME

alias build := fuzzer

fuzzer:
    cargo build --profile={{ PROFILE }} --features=tui

run: fuzzer
    {{ FUZZER }}

clean:
    cargo clean
